---

- name: "Conf directory present"
  file:
    path: "{{ pureftpd_etcdir }}"
    state: directory

- name: "Auth directory present"
  file:
    path: "{{ pureftpd_etcdir }}/auth"
    state: directory
  when: use_confdir

- name: "Config directory present"
  file:
    path: "{{ pureftpd_etcdir }}/conf"
    state: directory
  when: use_confdir

- name: "Default confdir values"
  copy:
    dest: "{{ pureftpd_etcdir }}/{% if item|lower in ['ldapconfigfile', 'mysqlconfigfile', 'pgsqlconfigfile', 'pamauthentication', 'puredb', 'unixauthentication'] %}auth{%else%}conf{% endif %}/{{ item }}"
    content: '{{ pureftpd_confdefaults[item] }}'
  with_items: "{{ pureftpd_confdefaults|difference(pureftpd_confvars) }}"
  when: use_confdir
  notify: reload pure-ftpd

- name: "Confdir values overrides"
  copy:
    dest: "{{ pureftpd_etcdir }}/{% if item|lower in ['ldapconfigfile', 'mysqlconfigfile', 'pgsqlconfigfile', 'pamauthentication', 'puredb', 'unixauthentication'] %}auth{%else%}conf{% endif %}/{{ item }}"
    content: '{{ pureftpd_confvars[item] }}'
  with_items: "{{ pureftpd_confvars }}"
  when: use_confdir and pureftpd_confvars
  notify: reload pure-ftpd

- name: "Create pure-ftpd.conf"
  copy:
    dest: "{{ pureftpd_etcdir }}/pure-ftpd.conf"
    content: |
        # Generated by Ansible
        # DO NOT EDIT MANUALLY
        #
        {% for key in pureftpd_confvars %}
        {{ key }}	{{ pureftpd_confvars[key] }}
        {% endfor %}
        {% for key in pureftpd_confdefaults|difference(pureftpd_confvars) %}
        {{ key }}	{{ pureftpd_confdefaults[key] }}
        {% endfor %}
  when: not use_confdir
  notify: reload pure-ftpd

- name: "User file present"
  template:
    src: "pure.passwd.j2"
    dest: "{{ pureftpd_etcdir }}/pure.passwd"
    owner: root
    mode: 0600
  register: update_userfile
  notify: reload pure-ftpd

- name: "Update userdb"
  command: "{{ pure_pw }} mkdb {{ pdb_file }} -f {{ pureftpd_etcdir }}/pure.passwd"
  when: update_userfile|changed

- name: "Link TLS certificate"
  file:
    dest: "{{ pure_certfile }}"
    src: "{{ pureftpd_ssl_certfile }}"
    state: link
  when: pureftpd_ssl_certfile is defined
  notify: reload pure-ftpd
