---

- name: "Custom fact directory present"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Pure-FTPd fact file present"
  copy:
    src: pureftpd.fact
    dest: /etc/ansible/facts.d/pureftpd.fact
    mode: 0755

- name: "Re-run setup to use custom facts"
  setup: ~
