---

- name: "Custom fact directory present"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Pure-FTPd fact file present"
  template:
    src: pureftpd.fact
    dest: /etc/ansible/facts.d/pureftpd.fact
    mode: 0755
  register: push_fact_script

- name: "Re-run setup to use custom facts"
  setup: ~
  when: push_fact_script|changed
