---

- name: "Auth directory present"
  file:
    path: "/etc/pure-ftpd/auth"
    state: directory

- name: "Config directory present"
  file:
    path: "/etc/pure-ftpd/conf"
    state: directory

- name: "Auth files present"
  template:
    src: "{{ item }}"
    dest: /etc/pure-ftpd/auth/
  with_fileglob:
    - ../templates/auth/*
  notify: reload pure-ftpd

- name: "Config files present"
  template:
    src: "{{ item }}"
    dest: /etc/pure-ftpd/conf/
  with_fileglob:
    - templates/conf/*
  notify: reload pure-ftpd

- name: "User file present"
  template:
    src: pure.passwd.j2
    dest: /etc/pure-ftpd/pure.passwd
    owner: root
    mode: 0600
  register: update_userfile
  notify: reload pure-ftpd

- name: "Update userdb"
  command: /opt/local/bin/pure-pw mkdb /opt/local/etc/pureftpd.pdb -f /etc/pure-ftpd/pure.passwd
  when: update_userfile|changed

- name: "Create symlink to pure.passwd"
  file:
    src: /etc/pure-ftpd/pure.passwd
    dest: /opt/local/etc/pureftpd.passwd
    state: link
  when: ansible_distribution == "SmartOS"

- name: "Create symlink to pure.pdb"
  file:
    src: /opt/local/etc/pureftpd.pdb
    dest: /etc/pure-ftpd/pure.pdb
    state: link
    force: yes
  when: ansible_distribution == "SmartOS"

- name: "check for SMF service presence (failure is ok)"
  shell: svcs -Ho state network/pure-ftpd
  register: smf_present
  ignore_errors: true
  changed_when: false

- name: "import SMF file"
  shell: svccfg import /opt/custom/smf/pure-ftpd-smf.xml
  when: smf_present|failed

