---
- include: facts.yml

#- debug: msg='{{ hostvars }}'

- name: check if user UIDs are correctly specified
  fail: msg='ERROR user "{{ item }}" does not have UID defined'
  when: pureftpd_users[item]['uid'] is undefined
  with_items: "{{ pureftpd_users }}"

- include: inst-smartos.yml
  when: ansible_distribution == "SmartOS"

- include: conf.yml

- include: post-inst-smartos.yml
  when: ansible_distribution == "SmartOS"

