---
- include: facts.yml

#- debug: msg='{{ hostvars }}'

- name: check if user UIDs are correctly specified
  fail: msg='ERROR user "{{ item }}" does not have UID defined'
  when: pureftpd_users[item]['uid'] is undefined
  with_items: "{{ pureftpd_users }}"

# define defaults
- name: set pure.pdb path (default)
  set_fact:
    pdb_file: '{{ pureftpd_etcdir }}/pure.pdb'

- name: set pure.pdb path (SmartOS)
  set_fact:
    pdb_file: '/opt/local/etc/pureftpd.pdb'
  when: ansible_distribution == "SmartOS"

- name: set pure-pw path (default)
  set_fact:
    pure_pw: 'pure-pw'

- name: set pure-pw path (SmartOS)
  set_fact:
    pure_pw: '/opt/local/bin/pure-pw'
  when: ansible_distribution == "SmartOS"

# Pure-FTPd from version 1.0.44 can directly use config files 
# and does not require wrappers anymore.
# Unfortunately, this version is not yet bundled 
# in SmartOS nor CentOS 7.
- name: determine config type
  set_fact:
    use_confdir: True

- include: inst-smartos.yml
  when: ansible_distribution == "SmartOS"

- include: conf.yml

- include: post-inst-smartos.yml
  when: ansible_distribution == "SmartOS"

